### ISSUE TITLE
add support for modded

### ISSUE THREAD

**Issue by peaceandcube** [jason-green-io/papyri#18]
Hello,
I have tried to render the map of my server using papyri and had this error:

```
map_*.dat nbt -> png: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18861/18861 [04:10<00:00, 75.42it/s]
level 4 of dim: 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:10<00:00,  6.08it/s]
level 4 of dim: 14: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.27it/s]
level 4 of dim: 15: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.33it/s]
level 4 -> zoom 17 tiles: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 71/71 [00:38<00:00,  1.82it/s]
zoom 16 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4544/4544 [00:29<00:00, 153.11it/s]
zoom 15 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1136/1136 [00:07<00:00, 149.10it/s]
zoom 14 tiles: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 284/284 [00:01<00:00, 142.97it/s]
zoom 13 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 71/71 [00:00<00:00, 134.14it/s]
zoom 12 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 54/54 [00:00<00:00, 230.33it/s]
zoom 11 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 249.09it/s]
zoom 10 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 262.95it/s]
zoom 9 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 270.05it/s]
zoom 8 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 264.25it/s]
zoom 7 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 271.93it/s]
zoom 6 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 263.55it/s]
zoom 5 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 280.18it/s]
zoom 4 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 258.12it/s]
zoom 3 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 286.98it/s]
zoom 2 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 294.23it/s]
zoom 1 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 289.78it/s]
zoom 0 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 290.44it/s]
Traceback (most recent call last):
  File "./papyri.py", line 715, in <module>
    main()
  File "./papyri.py", line 706, in main
    genMapIdMarkers(maps, args.output)
  File "./papyri.py", line 636, in genMapIdMarkers
    "dimension": dimDict[dimension],
KeyError: 14

```
Do you please have an idea how to make it work ?

Many thanks.

**Comment by greener-dot-ca** [comment]
Are you running a modded server by any chance?

**Comment by peaceandcube** [comment]
Many thanks for your reply

I am running a 1.15.2 paper spigot server with a map that is ~6 years old and very large.

**Comment by greener-dot-ca** [comment]
Gotcha, modded server name the dimension region folders differently. Should be an easy fix.

**Comment by peaceandcube** [comment]
Great news, many thanks for renderer <3

**Comment by greener-dot-ca** [comment]
Would you mind providing me a listing of your world folder structure? I'm trying to find a concise way to find the region files regardless of vanilla or modded folder structures.

**Comment by peaceandcube** [comment]
Sure please find below contents of <server>/world/ folder:

**Folders:**
advancements  
data (chunks.dat idcounts.dat raids.dat scoreboard.dat and 18518 map_XXX.dat files)
datapacks  
generated 
playerdata  (players .dat file)
poi  
region (192688 .mca files)
stats

**Files:**
007mimi.dat
level.dat 
level.dat_old 
session.lock  
uid.dat

Please let me know if you need more

Many thanks

**Comment by greener-dot-ca** [comment]
Do you have any DIM folders? Or world_nether and world_the_end?

**Comment by peaceandcube** [comment]
Yes I do,

Root of the server contains folders:
world
world_the_end
world_nether

Content of world has been developed higher in the thread, please find below content of:

**world_nether:**
_Folders:_
DIM-1 which contains 3 folders:
------>data (1 file in it : raids_nether.dat)
------>poi (.mca files)
------>region (.mca files)
playerdata (empty)

_Files:_
level.dat
level.dat_old
session.lock
uid.dat


world_the_end has the same structure

**Comment by greener-dot-ca** [comment]
Can you please pull the dev branch and see if that works for you? It now auto detects the region files, so it should find them in modded and vanilla folder structures.

**Comment by peaceandcube** [comment]
Wow! Thanks for doing this <3!

Please find below the new output:
2020-04-05 19:14:08,172 Found Overworld regions in /home/fluub/dl/212.83.189.126/world/region
2020-04-05 19:14:08,192 Found maps in /home/fluub/dl/212.83.189.126/world/advancements/data
2020-04-05 19:14:08,214 Found maps in /home/fluub/dl/212.83.189.126/world/data
map_*.dat nbt -> png: 100%|███████████████| 18986/18986 [04:18<00:00, 73.33it/s]
Traceback (most recent call last):
  File "./papyri.py", line 751, in <module>
    main()
  File "./papyri.py", line 724, in main
    mcaFilesList = getMcaFiles(dataDict["regions"])
  File "./papyri.py", line 581, in getMcaFiles
    for mcaFile in regionDict[dim]:
KeyError: -1

**Comment by greener-dot-ca** [comment]
alright, try specifying `/home/fluub/dl/212.83.189.126` as your `--world`

**Comment by peaceandcube** [comment]
Sure, please find below the new output:
2020-04-05 19:36:09,559 Found Overworld regions in /home/fluub/dl/212.83.189.126/Eventd/region
2020-04-05 19:36:09,559 Found Overworld regions in /home/fluub/dl/212.83.189.126/plugins/Essentials/Event/region
2020-04-05 19:36:09,561 Found Nether regions in /home/fluub/dl/212.83.189.126/world_nether/DIM-1/region
2020-04-05 19:36:09,562 Found Overworld regions in /home/fluub/dl/212.83.189.126/Lost/region
2020-04-05 19:36:09,562 Found Nether regions in /home/fluub/dl/212.83.189.126/Lost/DIM-1/region
2020-04-05 19:36:09,563 Found End regions in /home/fluub/dl/212.83.189.126/world_the_end/DIM1/region
2020-04-05 19:36:09,563 Found Overworld regions in /home/fluub/dl/212.83.189.126/world_backup/region
2020-04-05 19:36:09,563 Found Overworld regions in /home/fluub/dl/212.83.189.126/avril/region
2020-04-05 19:36:09,777 Found Overworld regions in /home/fluub/dl/212.83.189.126/world/region
2020-04-05 19:36:09,778 Found Overworld regions in /home/fluub/dl/212.83.189.126/creatif/region
2020-04-05 19:36:09,789 Found Overworld regions in /home/fluub/dl/212.83.189.126/Eventp/region
2020-04-05 19:36:09,790 Found maps in /home/fluub/dl/212.83.189.126/Lost/data
2020-04-05 19:36:09,809 Found maps in /home/fluub/dl/212.83.189.126/world/advancements/data
2020-04-05 19:36:09,831 Found maps in /home/fluub/dl/212.83.189.126/world/data
map_*.dat nbt -> png: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18986/18986 [04:22<00:00, 72.46it/s]
level 4 of dim: 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:10<00:00,  5.94it/s]
level 4 of dim: 15: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.05it/s]
level 4 of dim: 16: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.70it/s]
level 4 of dim: 14: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.09it/s]
level 4 -> zoom 17 tiles: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74/74 [00:39<00:00,  1.86it/s]
zoom 16 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4736/4736 [00:34<00:00, 137.23it/s]
zoom 15 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1184/1184 [00:08<00:00, 144.57it/s]
zoom 14 tiles: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:02<00:00, 139.16it/s]
zoom 13 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 133.12it/s]
zoom 12 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 223.68it/s]
zoom 11 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:00<00:00, 230.14it/s]
zoom 10 tiles: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:00<00:00, 243.27it/s]
zoom 9 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [00:00<00:00, 258.87it/s]
zoom 8 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 255.01it/s]
zoom 7 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 272.81it/s]
zoom 6 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 254.83it/s]
zoom 5 tiles: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 263.19it/s]
zoom 4 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 245.16it/s]
zoom 3 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 280.60it/s]
zoom 2 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 264.31it/s]
zoom 1 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 278.16it/s]
zoom 0 tiles: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 249.05it/s]
Traceback (most recent call last):
  File "./papyri.py", line 751, in <module>
    main()
  File "./papyri.py", line 742, in main
    genMapIdMarkers(maps, args.output)
  File "./papyri.py", line 673, in genMapIdMarkers
    "dimension": dimDict[dimension],
KeyError: 15

**Comment by greener-dot-ca** [comment]
Seems like the maps you have refer to a dimension that isn't -1, 0 or 1. I imagine a plugin creates these. I need to skip these, or find out where they com from and render them.

**Comment by peaceandcube** [comment]
I think it does come from this plugin now that you say it :
https://www.spigotmc.org/resources/magic.1056/

It does have a camera spell that can render player heads on maps or even pictures from url

Could it be ignored during the rendering process if it does not have a dimension of -1 0 or 1 ?

**Comment by greener-dot-ca** [comment]
Yup, that's what I just added. It tries to generate an overlay of all the region files you have, but that gets complicated in modded. So it's optional now, I'll have to work on figuring out how to do it properly. Try the latest commit.

**Comment by greener-dot-ca** [comment]
Forgot to mention, delete the entire output folder to flush out the bad map png files.

**Comment by peaceandcube** [comment]
You sir are a very nice person:

http://play.peaceandcube.fr/map
(centered on our spawn: http://play.peaceandcube.fr/map/#17/200177.50000/-299689.75000/O)

Many thanks for all of this <3 from all our community!

You rock!!!

**Comment by greener-dot-ca** [comment]
De rien :)

**Comment by greener-dot-ca** [comment]
re opening to track progress for actual modded support
