### ISSUE TITLE
Setting zoomlevel crashes out

### ISSUE THREAD

**Issue by tomas-samot** [jason-green-io/papyri#2]
When I call the below:
`python3 papyri.py --mcdata ~/minecraft_servers/mc/minecraft/world --output template --zoomlevel 8`

I receive the following error message:
```

2018-02-28 23:01:18,538 Namespace(mapstats=False, mcdata='/home/tomas/minecraft_servers/mc/minecraft/world', nostitch=True, output='template', overlay=False, poi=False, zoomlevel='8')
Traceback (most recent call last):
  File "papyri.py", line 77, in <module>
    canvasSize = 2 ** (8 + args.zoomlevel)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by greener-dot-ca** [comment]
Please pull the latest commit and see if that still persists. That bug was present a few commits ago, but should be fixed now, just looking at the section of code, the canvasSize calculation casts args.zoomlevel to an int now, should be good.

**Comment by tomas-samot** [comment]
I am on the newest commit. Running on Ubuntu server 16.04.4. Python 3.5.2.

**Comment by greener-dot-ca** [comment]
I hadn't actually pushed the fix when I first encountered it, oops.

Try now.

**Comment by tomas-samot** [comment]
Yes that works now. Thank you
