### ISSUE TITLE
ValueError: invalid literal for int() with base 10: String('minecraft:overworld')

### ISSUE THREAD

**Issue by Sophira** [jason-green-io/papyri#23]
Hi,

First off, thank you so much for making this project. It's pretty much exactly what I want in a server-side map viewer and I'm so glad this exists.

I recently created a small, private Minecraft server (1.16.3, but we plan to keep it updated to the latest release on each update) for me and my family, and we're trying to use Papyri to create a browseable map we can use. I'm on the latest commit as of right now ([1ce7743](https://github.com/jason-green-io/papyri/commit/1ce77431ac7a718486772ef9a0faf7a364c376a9)) but when trying to create the map, we get an error:

    (papyri-virtualenv) mineserver@matrix ~/papyri $ python papyri.py --world $HOME/minecraft-server/worlds/matrixcraft/world --output $HOME/www/map --copytemplate
    map_*.dat nbt -> png:   0%|                                                              | 0/24 [00:00<?, ?it/s]
    Traceback (most recent call last):
      File "papyri.py", line 715, in <module>
        main()
      File "papyri.py", line 685, in main
        makeMapPngJava(args.world, mapsOutput, unlimitedTracking=args.includeunlimitedtracking)
      File "papyri.py", line 335, in makeMapPngJava
        mapDim = int(mapNbt["data"]["dimension"])
    ValueError: invalid literal for int() with base 10: String('minecraft:overworld')

Is there something I'm doing incorrectly?

**Comment by Sophira** [comment]
Oh, I forgot to mention - I'm using Python 3.7.8 in a virtualenv environment that has these modules installed:

    (papyri-virtualenv) mineserver@matrix ~/papyri $ pip list
    Package    Version
    ---------- -------
    nbtlib     1.7.0
    numpy      1.19.2
    Pillow     7.2.0
    pip        20.2.3
    setuptools 50.3.0
    tqdm       4.49.0
    wheel      0.35.1

**Comment by greener-dot-ca** [comment]
I ran into this in 1.16 .. Mojang started using the string names for dimensions instead of the integer values in the .dat nbt. It's fixed in the dev branch, which includes a bunch of other stuff. Try it out.

**Comment by Sophira** [comment]
Thank you! That did indeed fix the issue. :) I'll go ahead and close this issue now.
