### ISSUE TITLE
Newer maps of same dimension, region and zoom level, overwrite older maps with white "unexplored" information

### ISSUE THREAD

**Issue by MnTronslien** [jason-green-io/papyri#28]
Noticed that a friend on the server had made a new map and was exploring the same region that I had spent most of my time in. When I went and check out my house I saw that much of my region was unexplored, despite me having an explored map for it.

The issue is probably that the code just takes the newest map and ignores older ones - on the presumtion that newer maps are the most up to date, but then you run into issues like this
Oldest - most explored map
![15 48c0594ef953d292919a4609c79e8ded 1607390244 minecraft@overworld 960 -1088 4](https://user-images.githubusercontent.com/16963894/101517108-a44c6800-3980-11eb-91c9-2e0d688cd58c.png)
Newest, barely explored map.
![71 b546038459917bb45d62358b395039f2 1607439867 minecraft@overworld 960 -1088 4](https://user-images.githubusercontent.com/16963894/101517111-a4e4fe80-3980-11eb-86b4-166d8dd5ec63.png)

I don't know how you would do it specifically, but I suggest that before sticking the tiles together, if there are several maps of the same dimensions and region, you merge them pixel by pixel by pixel, replacing pixels from the oldest map with pixels from the newest map only if the pixel on the newer map isn't transparent.

**Comment by greener-dot-ca** [comment]
This is how it should be done and is fixed in 2.0.2 .. which isn't merged with master yet.

**Comment by MnTronslien** [comment]
Awesome - looking forward to testing it out :)

**Comment by TheSabotender** [comment]
any ETA on 2.0.2? our server has many players, and we have noticed this issue several times :P

**Comment by greener-dot-ca** [comment]
You can try out the `dev` branch, pretty sure it has the fixes applied, I just haven't pulled them to master since I'll be doing the Windows fixes at the same time.

**Comment by greener-dot-ca** [comment]
Nevermind, I just pulled in 2.0.2 .. I'll do the Windows fixes in 2.0.3 :)
