### ISSUE TITLE
`.dzi` files are named with two extentions & Resources missing to load webpage

### ISSUE THREAD

**Issue by tomas-samot** [jason-green-io/papyri#3]
```
0.-16448.-64.dzi.dzi
0.-16448.-64.dzi_files
0.-64.-16448.dzi.dzi
0.-64.-16448.dzi_files
0.-64.-64.dzi.dzi
0.-64.-64.dzi_files
```
These files seem to be named wrong. When you launch a web server, it fails to find the content because it looks for the file `0.-16448.-64.dzi`.

This happens after generating for the first time.

The directory also is also missing `images` and `openseadragon`.

**Comment by greener-dot-ca** [comment]
I run into this problem between MacOS and Linux. For some reason pyvips decides to name the output dzi files differently depending on the platform. Right now, this works on Ubuntu. What platform are you running it on?

**Comment by tomas-samot** [comment]
I am running Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64). Python 3.5.2.

*edit
I have a separate problem but I don't wish to raise another issue. I will if you are okay with me raising it.
Large sections of the map are very pixelated. Could I be lacking resources to render correctly? (I'm out of ideas as to why this is happening)
Server spec:
CPU: AMD FX(tm)-4300 Quad-Core Processor
RAM: 16GB
SSD system drive.

**Comment by greener-dot-ca** [comment]
New issue is fine.

The `dzi` is solved, not sure why openseadragon and the images aren't copying over for you. May have to do with how I detect the current working directory.

**Comment by tomas-samot** [comment]
`0_-64_-64.png  0_-64_-65600.dzi  0_-64_-65600_files  0_-64_-65600.png`

I got this out well generating a new map.

Just need to move two folders `template/images` & `template/openseadragon`.

*Edit
Here is the map: `samot.ninja`

**Comment by greener-dot-ca** [comment]
I'm unable to view the map at that address. The pixellation could be related to an option I set in the index.html files.

If you remove the output folder, does it copy over the `images` and `openseadragon`?

**Comment by tomas-samot** [comment]
I pulled the latest master branch.

It errors out asking for `--output` flag. 

```
$ python3 papyri.py --mcdata ~/minecraft_servers/mc/minecraft/world
usage: papyri.py [-h] [--poi] --mcdata MCDATA --output OUTPUT
                 [--zoomlevel ZOOMLEVEL] [--overlay] [--nostitch] [--mapstats]
papyri.py: error: the following arguments are required: --output
```

or if I give it an empty flag it expects an argument.

```
$ python3 papyri.py --mcdata ~/minecraft_servers/mc/minecraft/world --output
usage: papyri.py [-h] [--poi] --mcdata MCDATA --output OUTPUT
                 [--zoomlevel ZOOMLEVEL] [--overlay] [--nostitch] [--mapstats]
papyri.py: error: argument --output: expected one argument
```

~What do you want me to try here?~

I ran this:
```
[~/minecraft_servers/map_gen/papyri]$ python3 papyri.py --mcdata ~/minecraft_servers/mc/minecraft/world --output map
```

and I got this directory this time:

```
[~/minecraft_servers/map_gen/papyri/map]$ ls
bigbook.png  images  index.html  index.md  itemframe.png  map  openseadragon
```

`python3 -m http.server 80`
Which works when I run the python server in these two locations:
```
map
map/map/overworld
```


> I'm unable to view the map at that address. The pixellation could be related to an option I set in the index.html files.

Seems like the python web server crashed out. I'll set up apache once I get this working.
What option is this?

I raise a separate issue for this.

**Comment by greener-dot-ca** [comment]
I meant delete your output folder and re-render with the same options. `--output` is always required.

**Comment by greener-dot-ca** [comment]
Always run the web server in the base of the output folder, otherwise the individual dimension index files can't pickup the dependencies from openseadragon. Closing this issue.
