### ISSUE TITLE
breaks with newer versions of nbtlib

### ISSUE THREAD

**Issue by jarekt** [jason-green-io/papyri#39]
Nbtlib removed the root attribute in 2.0.0 (https://github.com/vberlier/nbtlib/releases/tag/v2.0.0) leading to an error on line 281 `mapNbt = mapNbtFile.root["data"]`: 'File' object has no attribute 'root'

Version 1.12.1 works well however.

This should be at least added to the readme.

**Comment by greener-dot-ca** [comment]
I'll update the code to stop loading `"root"` and ensure the pip instructions get `nbtlib>=2.0.1`.

**Comment by greener-dot-ca** [comment]
merged a change that fixes this
