### ISSUE TITLE
Pixelated map view

### ISSUE THREAD

**Issue by tomas-samot** [jason-green-io/papyri#4]
When viewing the map it seems to be rendered pixelated.

![screenshot at mar 06 9-51-04 am](https://user-images.githubusercontent.com/15977784/37025923-dc123c78-2124-11e8-90e6-060b483f28bd.png)
![screenshot at mar 06 9-58-35 am](https://user-images.githubusercontent.com/15977784/37025955-f3df256e-2124-11e8-83aa-a599060dfa49.png)

**Comment by greener-dot-ca** [comment]
That is normal, what you are seeing is a zoom level 4 map being rendered underneath maps of lower zoom levels. If you want more detail in those areas, map the area with a lower level map.

**Comment by tomas-samot** [comment]
Something like this?
`$ python3 papyri.py --mcdata ~/minecraft_servers/mc/minecraft/world --output map --zoomlevel 1`

**Comment by greener-dot-ca** [comment]
I meant in the game. You'd need to explore those areas in game with a lower level map.

**Comment by tomas-samot** [comment]
Oh. Is there a way to avoid having to do that?

**Comment by greener-dot-ca** [comment]
Nope, Papyri can only render what's been generated as in game maps.

**Comment by tomas-samot** [comment]
Okay. Sorry for the misunderstanding.
Closing the issue.
