### ISSUE TITLE
Extra dependency to install

### ISSUE THREAD

**Issue by oodgaard** [jason-green-io/papyri#5]
I had to also install libffi-dev (ubuntu 16.04)

**Comment by greener-dot-ca** [comment]
Thanks, I'll update the README.md


On Wed, Mar 14, 2018, at 8:27 AM, Otto wrote:
> I had to also install libffi-dev (ubuntu 16.04)


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/jason-green-io/papyri/issues/5
