### ISSUE TITLE
Program generating blank html page / Custom maps placing at 0,0

### ISSUE THREAD

**Issue by Conclavidor** [jason-green-io/papyri#7]
After messing around with files for a couple hours to get the mapper to work (don't use python a lot), I finally managed to get everything to render. The index.html file only loads to a blank gray page, however. 

Hosted the page anyway, so here is where I'm at:
http://papyri.dasfaust.com/

Complete render log:
[renderlog.log](https://github.com/jason-green-io/papyri/files/2498645/renderlog.log)

**Comment by greener-dot-ca** [comment]
Seems the index.html page can't find some resources, namely openseadragon .. and probably a bunch of other stuff. The root of the output folder needs to be served, that's where openseadragon (the deep zoom viewer) and all the banner images get generated. So in your case, everything in Papyri and children need to be served.

**Comment by Conclavidor** [comment]
So the problem is it doesn't know where to call for those files after generation? I have the same blank screen trying to view index.html locally, so it's not a hosting problem. Is there somewhere specific I can put the output to avoid this problem? I tried outputting a folder directly in the root Papyri folder and still have the same result.

You say "serve the files", but I'm just not familiar enough with scripting to know where in the process to do that. Sorry. =<

**Comment by greener-dot-ca** [comment]
Try putting your output folder, according to the log, called `Papyri`, into the root of your web server and go to http://papyri.dasfaust.com/Papyri/map/overworld

**Comment by Conclavidor** [comment]
Thank you!!
Mixed success! Got it working, though I still feel like the whole setup is a little awkward. I'm using Apache to host, so I don't have any one "true" root for my dasfaust.com website - though I set it like you suggested.
http://dasfaust.com/user-maps.html

I managed to get the desired result by putting the output folder in Papyri/template to give index.html access to the files it wanted. I noticed that I wasn't able to open index.html successfully locally with Chrome, only Microsoft Edge (security issues?) - so maybe that was giving me more of a headache early on? Although I wasn't able to get the openseadragon UI to display until I had "maps" and "templates" in the same folder. Shouldn't these export into the output folder as well?

- - - -
At any rate - now I've noticed a new problem. Papyri doesn't know what to do with custom maps, so it just sticks them right in the middle of the map. This is amusing, though obviously undesirable.
http://papyri.dasfaust.com/template/map/overworld/#zoom=0.000995411072257785&x=6.981308061480127&y=0.044284747816954205

I used the MC Map Item Tool to make this map, for reference. Maybe they set the dimension for their maps to 0,0 since it wouldn't normally be a problem? If that's the case then I know it's not your fault, but I figured I should bring it up anyway.
https://mc-map.djfun.de/

**Comment by greener-dot-ca** [comment]
The Python module should copy the contents of template into the output folder. I'm guessing it bugs out in Windows (never tested it). I'm glad you figured it out! Might be worth me spinning up a Windows VM and get it consistently working in Windows.

Yup, the NBT on that map must put it's centre at origin. If you want to fix it, mc-map.djfun.de seems to allow you set the centre of the map. You could recreate Nic Cage somewhere else so he's not smack dab in the middle :)

**Comment by Conclavidor** [comment]
I'm glad, too! lol
Thanks for the help, I'll try to work out the Cage problem on my own, starting with that tool.
